### ISSUE TITLE
core3.0下可以完整运行吗？

### ISSUE THREAD

**Issue by david-nono** [SmallChi/JT808Gateway#3]
作者你好！看了你的项目觉得做得很好，可以联系吗？

**Comment by SmallChi** [comment]
可以直接运行的。

**Comment by david-nono** [comment]
我在Centos下直接编译的，运行SimpleServer.dll时候报错：
Unhandled exception. System.TypeLoadException: Method 'UseServiceProviderFactory' in type 'Microsoft.Extensions.Hosting.HostBuilder' from assembly 'Microsoft.Extensions.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at JT808.DotNetty.SimpleServer.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at JT808.DotNetty.SimpleServer.Program.Main(String[] args)
   at JT808.DotNetty.SimpleServer.Program.<Main>(String[] args)
Aborted
不知道问题出在哪里，需要在windows环境下编译吗？对.net core不是很熟

**Comment by SmallChi** [comment]
抱歉，上次忘记提交老的demo,这个新的是可以https://github.com/SmallChi/JT808DotNetty/tree/master/src/JT808.Gateway.SimpleServer 老的明天升级下

**Comment by david-nono** [comment]
2711688370@qq.com
如果方便的话可以邮件联系下，希望可以合作，谢谢！
